<h3>What are my beliefs, values and understandings?</h3>
<p>Teachers have the potential to effect reconciliation and redress educational inequities. Building trust is an imperative.. An ethic of care is the foundation for all teaching practices. The belief that all students can achieve to the level expected for their age, despite, and also due to, a diversity of knowledge, culture, language brought to school from home. All students are regarded as having the capacity to learn. Knowledge of the legacy of Australia's educational history and Aboriginal and Torres Strait Islander perspectives on curriculum content endows teaching with respect, humility and flexibility. Awareness of community aspirations for their children's education informs teaching.</p>
<br>
<h3>How can my cultural experience assist in building cultural bridges to facilitate learning?</h3>
<p>Valuing students' cultural identity includes showing respect for students' home language and knowledge, family and community, values and beliefs. Furthermore, local community members and cultural knowledges and values are welcomed into the classroom and used to scaffold children's learning. Education about oppression and authentic Aboriginal and Torres Strait Islander perspectives are included in the curriculum. Indigenous staff that are positive role models and engage with students and family are critical members of the school. Schools support teachers' pursuit of student academic and social outcomes by providing an accessible process by which students and community can be included in school decision making. Schools provide staff time to visit families at home and organise cross-cultural training from community Elders. Strategies to maximise student attendance at school include facilitating student re-enrolment and transitions from other schools and supporting students' educational pathway. School administration provides professional development for Aboriginal or Torres Strait Islander teacher aides to maximise their teaching roles. School provides access to cultural peer support and role models for Aboriginal and Torres Strait Islander students.</p>
<br>
<h3>How do I make my teaching explicit?</h3>
<p>Expectations of students both in behaviour and achievement, and the direction of future learning are clearly and repeatedly communicated to students. The knowledge and skills needed by students are explained and modelled in a variety of ways especially through concrete example. Many examples are given to ensure students have seen and understand what is required of them in working towards learning goals. Constructive feedback is regularly given to students as they learn. There is a tendency towards explicit instruction, emphasizing a gradual release of responsibility, but inquiry-based learning is encouraged, especially in regards to student initiated questions and ideas.</p>
<br>
<h3>In which ways do I differentiate my teaching to accommodate student diversity and promote student self-regulation?</h3>
<p>All students are unique, so multiple learning trajectories and experiences that cater for a variety of learning preferences are provided. The teacher establishes individual goals for student achievement, gives individual feedback and provides intervention for students not meeting expected achievement. Students understand their learning goals and work towards these goals through self-regulated learning which requires perseverance and teacher and peer support. Gifted students are identified and supported for extended learning even if literacy levels are low. Individual strengths of students are used as foundations for supporting collective learning.</p>
<br>
<h3>What are characteristics of an ethic of care that contributes to learning?</h3>
<p>The teachers' role is to facilitate learning; this is achieved through an ethic of care characterised by respectful, positive and warm interactions with students. Teachers communicate their regard for all dimensions of learning, including social development, not just academic achievement. Teachers can demonstrate their care for students through verbal and no-verbal interactions outside of the classroom, and pursuit of high expectations in the classroom. Student health and wellbeing underpin academic and social development. Students with individual needs, such as hearing loss, have access to support services. Strategies advocated by specialists are enacted in the classroom. In addition to creating a supportive learning environment, vigilance in detecting the need to refer students to specialist services is the essence of an ethos of care.</p>
<br>
<h3>How do I teach literacy?</h3>
<p>Literacy is taught from a foundation of spoken language. There is an acute awareness by teachers and students that literacy demands are often the major obstacle to learning and demonstrating learning. Teachers assist students in navigating the literacy demands of schooling. Code switching between Aboriginal English and Standard Australian English is explicitly taught. Students are orientated to age appropriate texts before reading; then reading strategies and writing are taught and repeatedly modelled in context. In addition, literacy is taught across the curriculum as the vocabulary, language features and text features of each curriculum area are explicitly taught. Shared reading is common. Visual images are commonly used to prompt conversation before textual reading.</p>
<br>
<h3>How can I support and advance student behaviour?</h3>
<p>Students contribute to the setting of classroom expectations, which are clearly and consistently communicated to students. The encouragement of cooperative behaviours, engaging and accessible tasks and use of routine decrease the need to manage student behaviours. Off-task behaviour is managed promptly with less invasive techniques such as non-verbal, proximity, pause and wait, close talk (private reprimands) or group reprimands. Student misconduct is addressed promptly with adherence to previously identified lines of action. The learning expectations of classrooms are not compromised by misbehaviour.</p>
<br>
<h3>What are my practices for causing learning?</h3>
<p>The teacher has a broad repertoire of pedagogical practices to cause learning. There is a tendency towards a gradual release of responsibility in teaching practice. The teacher behaves as a learning facilitator rather than an authority figure and students are given choices, open ended, experiential, group and outside activities from which to learn. The use of narrative to provide context for learning is frequent. Visual imagery is used to prompt engagement and support learning. A holistic approach is usually taken, in which information and skills are chunked and scaffolded, and connected to prior knowledge. Students are provided time to gain mastery of skills, to reflect and to self-assess, especially through tasks that involve working to end type products. Individual feedback is given and learning success is celebrated. Communication of ideas, especially abstract tasks, occurs orally when students are engaged physically with learning tasks. Explanation of ideas is succinct. Teachers under-talk rather than over-talk.</p>
<br>
